---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ttf-mscorefonts-installer
    ansible_connection: ssh
    ansible_host: "{{ args_msfonts_ipaddress }}"
  become: true

