namespace: alex

name: ms

version: 1.0.4
## TODO Autiomate using the build command

readme: README.md

authors:
- Alexander Witteveen <alex.witteveen@live.nl>

description: a ansible collection - installing MS dotnet, powershell

tags: []

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

repository: https://github.com/AlexWitteveen/ALEX.Ansible.MS

documentation: https://github.com/AlexWitteveen/ALEX.Ansible.MS/blob/main/README.md

