---

- name: "Playbook: Install Microsoft stuff"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.ms.server

    - ansible.builtin.include_role:
        name: alex.ms.desktop

