---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - wget 
    - apt-transport-https 
    - software-properties-common

- name: Download dotnet deb
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: ~/packages-microsoft-prod.deb

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - powershell

